### PR TITLE
No longer need to give primary frametype argument when using custom TimeSeries file

### PR DESCRIPTION
**Pull request by wutmeownow**
Fix for unnecessary error when using a custom TimeSeries file and not giving primary frametype argument.  Since reading a TimeSeries file does not require a frametype, it makes sense that users shouldn't have to give a frametype. I essentially added an and statement to line 481 to check if a TimeSeries file is being used, and if so, it does not try to get the frametype.

### CODE REVIEW

**Comment by wutmeownow** [comment]
It seems the build and test is failing due to #409. Not sure why Lint / rstcheck fails.

**Comment by eagoetz** [comment]
@wutmeownow Can you rebase this? Hopefully the CI build should pass

**Comment by wutmeownow** [comment]
> @wutmeownow Can you rebase this? Hopefully the CI build should pass

Ah, I'm not familiar with rebasing. What command would I use?

**Comment by eagoetz** [comment]
> Ah, I'm not familiar with rebasing. What command would I use?

As an example for keeping your fork and feature branch up-to-date, see https://git.ligo.org/lscsoft/lalsuite/-/blob/master/CONTRIBUTING.md#keeping-your-fork-up-to-date

**Comment by wutmeownow** [comment]
I'm gonna close and reopen and see if that makes the workflow run.

**Comment by robertbruntz** [comment]
@eagoetz Is this ready to be merged now?

**Comment by eagoetz** [comment]
I think this is ok. I don't see any specific problems

**Review by eagoetz — APPROVED** [review]
LGTM

**Pull request merged**
